language: elixir
elixir: 1.3.2
cache:
  directories:
  - _build
  - deps
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: nU91gKbUeSz6awecoIY+6tW5jRVJ0zEr6GXSCw2uQcoVkka/HMN5dpfPCU9TdVxumNts2Q39CCqM5YYGVMbVZX3Oh83XwT0lxSHfn3zWUEbLo8SPhCGjfRpySqFE05WiptmSNfq8mPNKEqM5NEd/+xzWLjG7QRuBcwMVUwrY1Au9dWUlPFvZBC+4T8ODiVj1BXvdqk0fjJkYKNVAoA3E1bxSlFpD5vP0oADLy5Ga6tjLR0dzn6OSX8Zpt0T02x3WZYH3I+eW1F+YdyP6S2Nxl0xE3Cwr48QtIOWUeNNSZnPpSmIbwHNZrVk2zzjRKDuiuXPW7pVSWR+RS0IE70zQMtyMVowZGBxglsDXi7ttpaFJvg6Y0fys4n8jhndzcxAW9kFp+aA71iFCvbnySZnfmasA3jdzWGrLbFBekFKZPXjA+KChGv0SJGjvHwBz2LOLK3ACPlfcYJ1BMRkzewT8uzUpmNfTm5o/JkMMubXav52t7BLXwLwPehsoU487r1AvrUl+uTQ1t46v5WZe2U7VaW+zOqeZV9LnbeIM9cAvyb4vdJpF5KPr111MU/eUPfSbb8bEU0LPNS11HvWIM0LfoXMpIymehnLPePwe78SXA5W5sjz/ZDNN5959Z8n/N0FEIJNmH//MA/aCvnhh3Z9hjK2WraFcLlzH6504asV0t7E=
