language: elixir
elixir: 1.3.2
cache:
  directories:
  - _build
  - deps
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: PxWpyKKK1odcvMsUD3hLLGACUZBeY4Kwy8E1bdSdga1rKrnayZ8058X6idMmbcF4KztmHXp5BNwUzZ27rT67yTxyYoRpnmXdgDvolCMYMVTEpM7aZZ++fr9mSERdKSnpUuddMxKQo3gBndzypDon5kid1M6TgdgqpkMxPd2NxrTAVXyr/KBh1kPote9WaFo4yfkMigqMOt4it7S44IklUBhFVPEunbkMPag9GPxmN76apmn68OE4v0vj/xed/V2t2uAhUatZPngflPlUDUuDz/enWJ3Mo4bAsolBHYmO/GJF5HReksZ9oFkd7DwKu0jmyX7ME9IIMm85tseb20lH8QbtNBCadxX1deDWawEYgHKnsGNKOBW+/f8i37tBox4P2v/wZ43Rj9eYvaBFsf5h4dvdhxvJoN9DhuFqAHtt0NKU5yXOod/imWLqeyt6XuuHST6sN2xeAP+c40nBYsbm/DtI4zEygIxxYVmWEUvsSbRfYWF6UPwQ41mptN4/c27AACaTiyLh7Y0QyUoeFXAFvxQyp79nCqEgwUx/EbFdkavKArqnP5X6HumJdAPAg/syudQIT5AU5X7AeSpY9PZp8/iVvDrrEU7+Iv/Dw6SlkR8bzDz00GdhuXitf0BWKZczBtHa8mneW1r4tvm8Z+TxOa1dC3y2REJuZ0yKW94+oI0=
