version: '2'
volumes:
  bundle:
  db:
  backend_deps:
  backend_build:

services:
  db:
    image: mysql:5.7
    volumes:
      - 'db:/var/lib/mysql'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

  web:
    extends:
      file: docker-compose-base.yml
      service: rails
    command: rails server -b 0.0.0.0
    depends_on:
      - db
    pid: host
    ports:
      - 3000:3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: mix phoenix.server
    working_dir: /backend
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - './backend:/backend'
      - 'backend_deps:/backend/deps'
      - 'backend_build:/backend/_build'

  ngrok:
    image: wernight/ngrok
    depends_on:
      - web
    ports:
      - 4040:4040
    environment:
      NGROK_PORT: 'web:3000'
