version: '2'
volumes:
  db:
  node_modules:
  deps:
  build:
  yarn-cache:

services:
  db:
    image: instedd/ask-mysql:5.7
    volumes:
      - 'db:/var/lib/mysql'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

  app:
    command: elixir --sname server -S mix phx.server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /app
    depends_on:
      - db
    volumes:
      - './:/app'
      - 'deps:/app/deps'
      - 'build:/app/_build'
    environment:
      DATABASE_HOST: db
      HTTP_PORT: 80
      TERM: xterm
    ports:
      - 80

  webpack:
    build:
      context: ./
      dockerfile: Dockerfile.webpack
    command: /bin/sh -c 'yarn install && yarn run watch'
    restart: always
    working_dir: /app
    stop_signal: SIGKILL
    volumes:
      - './:/app'
      - 'deps:/app/deps'
      - 'node_modules:/app/node_modules'
      - 'yarn-cache:/usr/local/share/.cache/yarn'

  ngrok:
    image: wernight/ngrok
    ports:
      - 4040
    environment:
      NGROK_PORT: 'app:80'
